import React from 'react';
import { motion } from 'framer-motion';

const WorksheetPreview = ({ selectedQRData, worksheetTitle }) => {
  const qrCodesPerPage = 12;
  const totalPages = Math.ceil(selectedQRData.length / qrCodesPerPage);
  
  const renderPage = (pageNumber) => {
    const startIndex = pageNumber * qrCodesPerPage;
    const endIndex = Math.min(startIndex + qrCodesPerPage, selectedQRData.length);
    const pageQRData = selectedQRData.slice(startIndex, endIndex);

    return (
      <motion.div
        key={pageNumber}
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        className="bg-white rounded-2xl shadow-2xl overflow-hidden mb-8"
        id={`worksheet-preview-${pageNumber}`}
      >
        <div className="w-full" style={{ width: '2480px', height: '3508px', transform: 'scale(0.25)', transformOrigin: 'top left' }}>
          <div className="p-32 h-full flex flex-col">
            <div className="text-center mb-24">
              <h1 className="text-9xl font-bold text-gray-800 mb-8">{worksheetTitle}</h1>
              <p className="text-4xl text-gray-600">Scan the QR codes below to access the links</p>
            </div>

            <div className="grid grid-cols-3 gap-20 justify-items-center justify-content-center mb-24 flex-grow">
              {pageQRData.map((qr, index) => {
                const qrImageUrl = `https://api.qrserver.com/v1/create-qr-code/?data=${encodeURIComponent(qr.url)}&size=600x600`;

                return (
                  <motion.div
                    key={qr.id}
                    initial={{ opacity: 0, scale: 0.9 }}
                    animate={{ opacity: 1, scale: 1 }}
                    transition={{ delay: index * 0.05 }}
                    className="w-full text-center"
                    style={{ maxWidth: '600px' }}
                  >
                    <div className="bg-gray-100 p-10 rounded-3xl border-4 border-gray-200 mb-8">
                      <img
                        src={qrImageUrl}
                        alt={`QR Code for ${qr.title}`}
                        className="w-full h-auto object-contain"
                        crossOrigin="anonymous"
                        style={{ width: '520px', height: '520px' }}
                      />
                    </div>
                    
                    <h3 className="text-4xl font-semibold text-gray-800 break-words leading-tight">
                      {qr.title}
                    </h3>
                  </motion.div>
                );
              })}
            </div>

            <div className="mt-auto flex justify-between items-center text-gray-500">
              <p className="text-3xl">Generated by QRIOS - QR Code Generator & Worksheet Builder</p>
              <p className="text-3xl">Page {pageNumber + 1} of {totalPages}</p>
            </div>
          </div>
        </div>
      </motion.div>
    );
  };

  return (
    <div>
      {Array.from({ length: totalPages }, (_, index) => renderPage(index))}
    </div>
  );
};

export default WorksheetPreview;